# Generated by Django 2.2.19 on 2021-12-06 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210425_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incart', 'В корзине'), ('check', 'Проверяется'), ('indeliver', 'Доставляется'), ('delivered', 'Доставлен')], max_length=300, verbose_name='Статус')),
                ('total_price', models.IntegerField(default=0, verbose_name='Итоговая стоимость')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Orders',
                'ordering': ['holder'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('side', models.CharField(choices=[('angel', 'Кровавые ангелы'), ('tiran', 'Тираниды'), ('none', 'Не выбрано')], max_length=300, verbose_name='Сторона')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'db_table': 'Shop',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 6, 13, 55, 51, 55696), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 6, 13, 55, 51, 55696), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('moder', 'Модераток'), ('admin', 'Администратор')], max_length=300, verbose_name='Роль')),
                ('choosedSide', models.CharField(choices=[('angel', 'Кровавые ангелы'), ('tiran', 'Тираниды'), ('none', 'Не выбрано')], max_length=300, verbose_name='Сторона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профили',
                'verbose_name_plural': 'Профили',
                'db_table': 'UserProfile',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SubOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость товаров')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orders', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shop', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары заказа',
                'db_table': 'SubOrders',
                'ordering': ['order'],
            },
        ),
    ]
