# Generated by Django 2.2.19 on 2021-12-06 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211206_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('models', 'Модельки'), ('books', 'Книги'), ('lands', 'Поля'), ('add', 'Дополнительные детали'), ('tshirt', 'Футболки'), ('shirt', 'Толстовки'), ('cosplay', 'Косплей'), ('figurki', 'Фигурки')], default='models', max_length=300, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 6, 16, 37, 48, 459971), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 6, 16, 37, 48, 459971), verbose_name='Дата'),
        ),
    ]
