# Generated by Django 2.2.19 on 2021-12-20 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211206_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('none', 'Не имеет размера')], default='none', max_length=100, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 20, 14, 16, 13, 121024), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 20, 14, 16, 13, 122023), verbose_name='Дата'),
        ),
    ]
