# Generated by Django 2.2.19 on 2021-12-20 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211220_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='size',
        ),
        migrations.AddField(
            model_name='shop',
            name='hasSize',
            field=models.BooleanField(default=False, verbose_name='Имеет размерность?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suborders',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('none', 'Не имеет размера')], default='none', max_length=100, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 20, 14, 43, 36, 101374), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 20, 14, 43, 36, 102373), verbose_name='Дата'),
        ),
    ]
