# Generated by Django 2.2.19 on 2022-05-16 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211220_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='hasSize',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='side',
        ),
        migrations.RemoveField(
            model_name='suborders',
            name='size',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='choosedSide',
        ),
        migrations.AddField(
            model_name='shop',
            name='hasMat',
            field=models.BooleanField(default=1, verbose_name='Выбор материала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suborders',
            name='material',
            field=models.CharField(choices=[('redwood', 'Красное дерево'), ('dub', 'Дуб'), ('elka', 'Ель'), ('none', 'Материал не выбирается')], default='none', max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 16, 22, 30, 50, 2282), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 16, 22, 30, 50, 2282), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('tables', 'Столы'), ('chairs', 'Кресла'), ('stool', 'Стулья'), ('sofa', 'Диваны'), ('bed', 'Кровати')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('moder', 'Модератор'), ('admin', 'Администратор')], max_length=300, verbose_name='Роль'),
        ),
    ]
